import json

with open(r'C:\Users\Rui Medalha\.claude\projects\C--Projetos-docflow-mvp\f9a22d4a-601e-4ed4-8d56-95cecd54dc3e\tool-results\mcp-overclock-overclock_catalog_uncategorized-1788779518989.txt', 'r', encoding='utf-8') as f:
    data = json.load(f)

RULES = {
    'scout': ['research','extract','map','locate','find','search','audit','investigate','analyze','trace','inspect','study','discover','explore','literature','citation','compar','look up','lookup','query','gather'],
    'reviewer': ['review','test','verif','check','critique','judge','validate','quality','bug','security','lint','sast','pentest','pen-test','penetration','hardening','scan','assert','catch bug'],
    'builder': ['build','design','architect','implement','create','scaffold','construct','code','write','generate','compose','set up','setup','package','deploy','develop','integrate','connect','wire','add','enable','launch','ship','publish','orchestrate','author','make plan','plan','automate','automation','optimize','fix','refactor','cleanup','migrat','sync','train','learn','coach','mentor','brief','explain','illustrate','document','documentat','spec','describe','walkthrough','tutorial','guide','reference','pattern','best practice','monitor','observe','instrument','track','measure','log','collect','capture','stream','route','dispatch','coordinate','teach','render','draw','convert','transform','configure','setup','craft']
}

def classify(name, desc):
    text = (name + ' ' + desc).lower()
    strong_reviewer = ['code review','security audit','bug-hunt','pen-test','penetration test','bug hunt','code-review','hardening','compliance check','accessibility audit','wcag audit','seo audit','compliance audit','audit a','audit the','audit ','checklist','bug finder','bug-hunt']
    strong_scout = ['literature review','citation','research-','research.','find bugs','locate','search for','lookup','look up']
    for s in strong_reviewer:
        if s in text: return 'reviewer'
    for s in strong_scout:
        if s in text: return 'scout'
    s_count = sum(1 for k in RULES['scout'] if k in text)
    r_count = sum(1 for k in RULES['reviewer'] if k in text)
    b_count = sum(1 for k in RULES['builder'] if k in text)
    if r_count > s_count and r_count > b_count:
        return 'reviewer'
    if s_count > b_count and s_count > r_count:
        return 'scout'
    return 'builder'

OVERRIDE = {
    'llm-prompt-optimizer': 'builder',
    'llm-structured-output': 'builder',
    'local-legal-seo-audit': 'builder',
    'local-llm-expert': 'builder',
    'logic-diff': 'reviewer',
    'logic-explain': 'scout',
    'logic-fix-all': 'builder',
    'logic-lens': 'reviewer',
    'logic-locate': 'scout',
    'logic-review': 'reviewer',
    'logistics-exception-management': 'builder',
    'loki-mode': 'builder',
    'longbridge': 'scout',
    'longbridge-content': 'scout',
    'longbridge-fundamentals': 'scout',
    'longbridge-market-data': 'scout',
    'lookdev': 'builder',
    'lookdev-auto': 'builder',
    'loop-library': 'builder',
    'loopy': 'builder',
    'lore': 'builder',
    'loss-aversion-designer': 'builder',
    'lovable-cleanup': 'builder',
    'luna': 'reviewer',
    'm365-agents-dotnet': 'builder',
    'm365-agents-py': 'builder',
    'm365-agents-ts': 'builder',
    'machine-learning-ops-ml-pipeline': 'builder',
    'macos-menubar-tuist-app': 'builder',
    'macos-screen-recorder': 'builder',
    'macos-spm-app-packaging': 'builder',
    'magic-animator': 'builder',
    'magic-ui-generator': 'builder',
    'mailchimp-automation': 'builder',
    'mailtrap-managing-contacts': 'builder',
    'mailtrap-sending-emails': 'builder',
    'mailtrap-setting-up-sending-domain': 'builder',
    'mailtrap-testing-with-sandbox': 'builder',
    'make-automation': 'builder',
    'make-plan': 'builder',
    'makepad-animation': 'builder',
    'makepad-basics': 'builder',
    'makepad-deployment': 'builder',
    'makepad-dsl': 'builder',
    'makepad-event-action': 'builder',
    'makepad-font': 'builder',
    'makepad-layout': 'builder',
    'makepad-platform': 'builder',
    'makepad-reference': 'builder',
    'makepad-shaders': 'builder',
    'makepad-skills': 'builder',
    'makepad-splash': 'builder',
    'makepad-widgets': 'builder',
    'malware-analyst': 'scout',
    'manage-skills': 'builder',
    'manifest': 'builder',
    'markdown-rendering': 'builder',
    'market-sizing-analysis': 'scout',
    'marketing-ideas': 'builder',
    'marketing-plan': 'builder',
    'marketing-psychology': 'scout',
    'marketing-strategy-pmm': 'builder',
    'markstream-install': 'builder',
    'mason': 'builder',
    'matematico-tao': 'reviewer',
    'material-design': 'builder',
    'mathguard': 'builder',
    'matplotlib': 'builder',
    'max': 'builder',
    'maxia': 'builder',
    'maximalism': 'builder',
    'mcp-builder': 'builder',
    'mcp-builder-ms': 'builder',
    'mcp-tool-developer': 'builder',
    'mdpr-skill': 'reviewer',
    'mem-search': 'scout',
    'memory-forensics': 'scout',
    'memory-safety-patterns': 'builder',
    'memory-systems': 'builder',
    'mental-health-analyzer': 'scout',
    'mercury-mcp': 'scout',
    'mermaid-diagrams': 'builder',
    'mermaid-expert': 'builder',
    'mesh-memory': 'builder',
    'metasploit-framework': 'builder',
    'micro-saas-launcher': 'builder',
    'microservices-patterns': 'builder',
    'microsoft-azure-webjobs-extensions-authentication-events-dotnet': 'builder',
    'microsoft-code-reference': 'scout',
    'microsoft-docs': 'scout',
    'microsoft-learn-cli': 'scout',
    'microsoft-skill-creator': 'builder',
    'microsoft-teams-automation': 'builder',
    'minecraft-bukkit-pro': 'builder',
    'minimalism': 'builder',
    'minimalist-ui': 'builder',
    'miro-automation': 'builder',
    'mise-configurator': 'builder',
    'mixpanel-automation': 'builder',
    'ml-engineer': 'builder',
    'ml-pipeline-workflow': 'builder',
    'mlops-engineer': 'builder',
    'mmx-cli': 'builder',
    'moatmri': 'scout',
    'mobile-design': 'builder',
    'mobile-developer': 'builder',
    'mobile-games': 'builder',
    'mobile-security-coder': 'builder',
    'mock-hunter': 'reviewer',
    'mode-creator': 'builder',
    'modellix': 'builder',
    'modern-javascript-patterns': 'builder',
    'molykit': 'builder',
    'monday-automation': 'builder',
    'monetization': 'builder',
    'monochromatic-ui': 'builder',
    'monopoly': 'builder',
    'monorepo-architect': 'builder',
    'monorepo-management': 'builder',
    'monte-carlo-analyze-root-cause': 'scout',
    'monte-carlo-asset-health': 'scout',
    'monte-carlo-monitor-creation': 'builder',
    'monte-carlo-monitoring-advisor': 'scout',
    'monte-carlo-performance-diagnosis': 'scout',
    'monte-carlo-prevent': 'reviewer',
    'monte-carlo-push-ingestion': 'builder',
    'monte-carlo-remediation': 'builder',
    'monte-carlo-storage-cost-analysis': 'scout',
    'monte-carlo-validation-notebook': 'builder',
    'moodle-external-api-development': 'builder',
    'moyu': 'reviewer',
    'mtls-configuration': 'builder',
    'multi-advisor': 'scout',
    'multi-agent-architect': 'builder',
    'multi-agent-brainstorming': 'scout',
    'multi-agent-patterns': 'builder',
    'multi-agent-task-orchestrator': 'builder',
    'multi-cloud-architecture': 'builder',
    'multi-platform-apps-multi-platform': 'builder',
    'multiplayer': 'builder',
    'n8n-code-javascript': 'builder',
    'n8n-code-python': 'builder',
    'n8n-expression-syntax': 'builder',
    'n8n-mcp-tools-expert': 'builder',
    'n8n-node-configuration': 'builder',
    'n8n-validation-expert': 'reviewer',
    'n8n-workflow-patterns': 'builder',
    'nanobanana-ppt-skills': 'builder',
    'native-data-fetching': 'builder',
    'ncbi-sequence-fetch': 'scout',
    'negentropy-lens': 'scout',
    'neo-brutalism': 'builder',
    'neon-ai-gateway': 'builder',
    'neon-functions': 'builder',
    'neon-object-storage': 'builder',
    'neon-postgres': 'builder',
    'neon-postgres-branches': 'builder',
    'neon-postgres-egress-optimizer': 'builder',
    'nerdzao-elite': 'builder',
    'nerdzao-elite-gemini-high': 'builder',
    'nestjs-expert': 'builder',
    'network-101': 'builder',
    'network-engineer': 'builder',
    'networkx': 'builder',
    'neumorphism': 'builder',
    'new-rails-project': 'builder',
    'newman-cicd-integration': 'builder',
    'news-sentiment-engine': 'builder',
    'nextjs-app-router-patterns': 'builder',
    'nextjs-best-practices': 'builder',
    'nextjs-seo-indexing': 'builder',
    'nextjs-supabase-auth': 'builder',
    'nft-standards': 'builder',
    'nika': 'builder',
    'nodejs-backend-patterns': 'builder',
    'nodejs-best-practices': 'builder',
    'nosql-expert': 'builder',
    'not-a-vibe-coder': 'builder',
    'not-human-search-mcp': 'scout',
    'notebooklm': 'scout',
    'notion-automation': 'builder',
    'notion-template-business': 'builder',
    'nutrition-analyzer': 'scout',
    'nx-workspace-patterns': 'builder',
    'objection-preemptor': 'builder',
    'observability-and-instrumentation': 'builder',
    'observability-engineer': 'builder',
    'observability-monitoring-monitor-setup': 'builder',
    'observability-monitoring-slo-implement': 'builder',
    'obsidian-bases': 'builder',
    'obsidian-cli': 'builder',
    'obsidian-clipper-template-creator': 'builder',
    'obsidian-markdown': 'builder',
    'oc-api-audit': 'reviewer',
    'oc-billing-webhooks': 'reviewer',
    'oc-storage-patterns': 'builder',
    'occupational-health-analyzer': 'scout',
    'odoo-accounting-setup': 'builder',
    'odoo-automated-tests': 'builder',
    'odoo-backup-strategy': 'builder',
    'odoo-docker-deployment': 'builder',
    'odoo-ecommerce-configurator': 'builder',
    'odoo-edi-connector': 'builder',
    'odoo-hr-payroll-setup': 'builder',
    'odoo-inventory-optimizer': 'builder',
    'odoo-l10n-compliance': 'builder',
    'odoo-manufacturing-advisor': 'builder',
    'odoo-migration-helper': 'builder',
    'odoo-module-developer': 'builder',
    'odoo-orm-expert': 'builder',
    'odoo-performance-tuner': 'builder',
    'odoo-project-timesheet': 'builder',
    'odoo-purchase-workflow': 'builder',
    'odoo-qweb-templates': 'builder',
    'odoo-rpc-api': 'builder',
    'odoo-sales-crm-expert': 'builder',
    'odoo-security-rules': 'builder',
    'odoo-shopify-integration': 'builder',
    'odoo-upgrade-advisor': 'builder',
    'odoo-woocommerce-bridge': 'builder',
    'odoo-xml-views-builder': 'builder',
    'odw': 'builder',
    'offers': 'builder',
    'office-productivity': 'builder',
    'oh-my-issues': 'scout',
    'on-call-handoff-patterns': 'builder',
    'onboarding': 'builder',
    'onboarding-cro': 'builder',
    'onboarding-psychologist': 'builder',
    'one-drive-automation': 'builder',
    'ontoly-software-graph': 'scout',
    'open-dynamic-workflows': 'builder',
    'open-source-marketing': 'builder',
    'openai-docs': 'scout',
    'openapi-spec-generation': 'builder',
    'openapi-spec-generator': 'builder',
    'openclaw-github-repo-commander': 'scout',
    'openfda-database': 'scout',
    'opentargets-database': 'scout',
    'optim-agent': 'builder',
    'options-flow-analyzer': 'scout',
    'oral-health-analyzer': 'scout',
    'orchestrate-batch-refactor': 'builder',
    'os-scripting': 'builder',
    'oss-hunter': 'scout',
    'osterwalder-canvas-architect': 'builder',
    'outlook-automation': 'builder',
    'outlook-calendar-automation': 'builder',
    'page-cro': 'reviewer',
    'pagerduty-automation': 'builder',
    'pagespeed-enhancer': 'reviewer',
    'paid-ads': 'builder',
    'pakistan-payments-stack': 'builder',
    'papers-skill': 'scout',
    'parallel-agents': 'builder',
    'pathfinder': 'scout',
    'patterns': 'builder',
    'payment-integration': 'builder',
    'paypal-integration': 'builder',
    'paywall-upgrade-cro': 'builder',
    'pc-games': 'builder',
    'pci-compliance': 'reviewer',
    'pdb-database': 'scout',
    'pdf': 'builder',
    'pdf-conversion-router': 'builder',
    'pdf-official': 'builder',
    'pentest-checklist': 'scout',
    'pentest-commands': 'builder',
    'performance-engineer': 'builder',
    'performance-optimization': 'builder',
    'performance-optimizer': 'builder',
    'performance-profiling': 'builder',
    'performance-testing-review-ai-review': 'reviewer',
    'performance-testing-review-multi-agent-review': 'reviewer',
    'permission-manager': 'builder',
    'personal-tool-builder': 'builder',
    'phase-gated-debugging': 'reviewer',
    'photopea-embedded-editor': 'builder',
    'php': 'builder',
    'php-pro': 'builder',
    'pi-custom-model': 'builder',
    'pi-web-search': 'scout',
    'pilot-protocol': 'builder',
    'pipecat-friday-agent': 'builder',
    'pipedrive-automation': 'builder',
    'pitch-psychologist': 'builder',
    'plaid-fintech': 'builder',
    'plan-writing': 'builder',
    'planejar-integracao-backlog': 'builder',
    'planning-and-task-breakdown': 'builder',
    'planning-with-files': 'builder',
    'playwright-java': 'builder',
    'playwright-skill': 'builder',
    'plotly': 'builder',
    'plugin-creator': 'builder',
}

items = data['items']
rows = []
for it in items:
    name = it['name']
    desc = it['description']
    key = it['identity_key']
    typ = it['type']
    cat = OVERRIDE.get(name)
    if not cat:
        cat = classify(name, desc)
    purpose = desc[:180].replace('\n', ' ').strip()
    rows.append({
        'identity_key': key,
        'type': typ,
        'name': name,
        'category': cat,
        'purpose': purpose,
        'when_to_use': 'See description.'
    })

with open(r'C:\Projetos\docflow-mvp\catalog-rows-1180.json', 'w', encoding='utf-8') as f:
    json.dump(rows, f, ensure_ascii=False)

from collections import Counter
c = Counter(r['category'] for r in rows)
print('Total rows:', len(rows))
print('Categories:', dict(c))
fallback = [r['name'] for r in rows if r['name'] not in OVERRIDE]
print('Fallback used on:', len(fallback))
if fallback:
    print('Sample fallback:', fallback[:20])
