import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { AuditAction, Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service'; import { AuditService } from '../audit/audit.service';
import { CreateMaintenanceDto, CreateMileageDto, CreateVehicleDto, ImputeFleetExpenseDto, UpdateVehicleDto } from './dto/fleet.dto';
@Injectable()
export class FleetService { constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  async createVehicle(tenantId: string, userId: string, dto: CreateVehicleDto) { const vehicle = await this.prisma.fleetVehicle.create({ data: { tenantId, ...dto } }); await this.log(tenantId, userId, AuditAction.CREATE, 'fleet_vehicle', vehicle.id); return vehicle; }
  listVehicles(tenantId: string) { return this.prisma.fleetVehicle.findMany({ where: { tenantId }, orderBy: { plate: 'asc' } }); }
  async getVehicle(tenantId: string, id: string) { return this.vehicle(tenantId, id); }
  async updateVehicle(tenantId: string, userId: string, id: string, dto: UpdateVehicleDto) { await this.vehicle(tenantId, id); const vehicle = await this.prisma.fleetVehicle.update({ where: { id }, data: dto }); await this.log(tenantId, userId, AuditAction.EDIT, 'fleet_vehicle', id); return vehicle; }
  async deleteVehicle(tenantId: string, userId: string, id: string) { await this.vehicle(tenantId, id); await this.prisma.fleetVehicle.delete({ where: { id } }); await this.log(tenantId, userId, AuditAction.DELETE, 'fleet_vehicle', id); return { id, deleted: true }; }
  async addMaintenance(tenantId: string, userId: string, vehicleId: string, dto: CreateMaintenanceDto) { await this.vehicle(tenantId, vehicleId); const row = await this.prisma.fleetMaintenance.create({ data: { tenantId, vehicleId, ...dto, date: new Date(dto.date) } }); await this.log(tenantId, userId, AuditAction.CREATE, 'fleet_maintenance', row.id); return row; }
  listMaintenance(tenantId: string, vehicleId: string) { return this.prisma.fleetMaintenance.findMany({ where: { tenantId, vehicleId }, orderBy: { date: 'desc' } }); }
  async addMileage(tenantId: string, userId: string, vehicleId: string, dto: CreateMileageDto) { await this.vehicle(tenantId, vehicleId); const row = await this.prisma.fleetMileage.create({ data: { tenantId, vehicleId, ...dto, date: new Date(dto.date) } }); await this.log(tenantId, userId, AuditAction.CREATE, 'fleet_mileage', row.id); return row; }
  listMileage(tenantId: string, vehicleId: string) { return this.prisma.fleetMileage.findMany({ where: { tenantId, vehicleId }, orderBy: { date: 'desc' } }); }
  async imputeExpense(tenantId: string, userId: string, vehicleId: string, dto: ImputeFleetExpenseDto) { await this.vehicle(tenantId, vehicleId); if (dto.type !== 'fuel' && dto.type !== 'toll') throw new BadRequestException('Expense type must be fuel or toll'); if (dto.documentId) { const document = await this.prisma.document.findFirst({ where: { id: dto.documentId, tenantId } }); if (!document) throw new NotFoundException('Document not found'); }
    const result = await this.prisma.$transaction(async (tx) => { const expense = await tx.expense.create({ data: { tenantId, amount: dto.amount, date: new Date(dto.date), supplier: dto.supplier, description: dto.description ?? `${dto.type} - vehicle ${vehicleId}`, category: `FLEET_${dto.type.toUpperCase()}`, documentId: dto.documentId, status: 'imputado' } }); const maintenance = await tx.fleetMaintenance.create({ data: { tenantId, vehicleId, date: new Date(dto.date), type: dto.type, description: `Expense ${expense.id}${dto.description ? `: ${dto.description}` : ''}`, cost: dto.amount, vendor: dto.supplier, receiptDocId: dto.documentId } }); return { expense, maintenance }; });
    await this.log(tenantId, userId, AuditAction.CREATE, 'fleet_expense_imputation', result.expense.id, { vehicleId, maintenanceId: result.maintenance.id, type: dto.type } as Prisma.InputJsonValue); return result; }
  private async vehicle(tenantId: string, id: string) { const row = await this.prisma.fleetVehicle.findFirst({ where: { id, tenantId } }); if (!row) throw new NotFoundException('Vehicle not found'); return row; }
  private log(tenantId: string, userId: string, action: AuditAction, entityType: string, entityId: string, metadata?: Prisma.InputJsonValue) { return this.audit.log({ tenantId, userId, action, entityType, entityId, metadata }); }
}
