import { ApiProperty, ApiPropertyOptional, PartialType } from '@nestjs/swagger';
import { FleetStatus } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsDateString, IsEnum, IsInt, IsNumber, IsOptional, IsString, Min } from 'class-validator';
export class CreateVehicleDto { @ApiProperty() @IsString() plate!: string; @ApiProperty() @IsString() brand!: string; @ApiProperty() @IsString() model!: string; @ApiPropertyOptional() @IsOptional() @IsString() vin?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() year?: number; @ApiPropertyOptional({ enum: FleetStatus }) @IsOptional() @IsEnum(FleetStatus) status?: FleetStatus; @ApiPropertyOptional() @IsOptional() @IsString() fuelType?: string; }
export class UpdateVehicleDto extends PartialType(CreateVehicleDto) {}
export class CreateMaintenanceDto { @ApiProperty() @IsDateString() date!: string; @ApiProperty({ example: 'oil' }) @IsString() type!: string; @ApiProperty() @Type(() => Number) @IsNumber() @Min(0) cost!: number; @ApiPropertyOptional() @IsOptional() @IsString() description?: string; @ApiPropertyOptional() @IsOptional() @IsString() vendor?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() mileage?: number; @ApiPropertyOptional() @IsOptional() @IsString() receiptDocId?: string; }
export class CreateMileageDto { @ApiProperty() @IsDateString() date!: string; @ApiProperty() @Type(() => Number) @IsInt() @Min(0) km!: number; @ApiPropertyOptional() @IsOptional() @IsString() purpose?: string; @ApiPropertyOptional() @IsOptional() @IsString() driverEmployeeId?: string; @ApiPropertyOptional() @IsOptional() @IsString() notes?: string; }
export class ImputeFleetExpenseDto { @ApiProperty({ enum: ['fuel', 'toll'] }) @IsString() type!: 'fuel' | 'toll'; @ApiProperty() @Type(() => Number) @IsNumber() @Min(0) amount!: number; @ApiProperty() @IsDateString() date!: string; @ApiPropertyOptional() @IsOptional() @IsString() documentId?: string; @ApiPropertyOptional() @IsOptional() @IsString() supplier?: string; @ApiPropertyOptional() @IsOptional() @IsString() description?: string; }
